// Code generated by tracegen. DO NOT EDIT.
// Source: testdata/full.go
package testdata

import (
	context "context"
	"encoding/json"
	"fmt"
	foobar "github.com/KazanExpress/tracegen/tracegen/testdata/bar"
	foo "github.com/KazanExpress/tracegen/tracegen/testdata/foo"
	attribute "go.opentelemetry.io/otel/attribute"
	codes "go.opentelemetry.io/otel/codes"
	trace "go.opentelemetry.io/otel/trace"
)

type TracedFull struct {
	base   Full
	tracer trace.Tracer
}

func NewTracedFull(_base Full, _tracer trace.Tracer) *TracedFull {
	return &TracedFull{
		base:   _base,
		tracer: _tracer,
	}
}
func (_d *TracedFull) A(ctx context.Context, id int64, text string) (bool, error) {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.A()")
	defer _span.End()
	_span.SetAttributes(attribute.Int64("id", id))
	_span.SetAttributes(attribute.String("text", text))
	_var0, _var1 := _d.base.A(ctx, id, text)
	if _var1 != nil {
		_span.RecordError(_var1)
		_span.SetStatus(codes.Error, _var1.Error())
	}
	return _var0, _var1
}
func (_d *TracedFull) B(ctx context.Context, foo *foo.Foo) foobar.Bar {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.B()")
	defer _span.End()
	if data, err := json.Marshal(foo); err == nil {
		_span.SetAttributes(attribute.String("foo", string(data)))
	} else {
		_span.SetAttributes(attribute.String("foo", fmt.Sprint(foo)))
	}
	_var0 := _d.base.B(ctx, foo)
	return _var0
}
func (_d *TracedFull) C(ctx context.Context, foo *foo.Foo) error {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.C()")
	defer _span.End()
	_span.SetAttributes(attribute.String("foo.Name", foo.Name))
	_var0 := _d.base.C(ctx, foo)
	if _var0 != nil {
		_span.RecordError(_var0)
		_span.SetStatus(codes.Error, _var0.Error())
	}
	return _var0
}
func (_d *TracedFull) D(ctx context.Context) {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.D()")
	defer _span.End()
	_d.base.D(ctx)
}
func (_d *TracedFull) E(ctx context.Context, bar []foobar.Bar) []foobar.Bar {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.E()")
	defer _span.End()
	if data, err := json.Marshal(bar); err == nil {
		_span.SetAttributes(attribute.String("bar", string(data)))
	} else {
		_span.SetAttributes(attribute.String("bar", fmt.Sprint(bar)))
	}
	_var0 := _d.base.E(ctx, bar)
	return _var0
}
func (_d *TracedFull) F(ctx context.Context, bars []*foobar.Bar) []*foobar.Bar {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.F()")
	defer _span.End()
	if data, err := json.Marshal(bars); err == nil {
		_span.SetAttributes(attribute.String("bars", string(data)))
	} else {
		_span.SetAttributes(attribute.String("bars", fmt.Sprint(bars)))
	}
	_var0 := _d.base.F(ctx, bars)
	return _var0
}
func (_d *TracedFull) G(ctx context.Context, bars *[]*foobar.Bar) *[]*foobar.Bar {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.G()")
	defer _span.End()
	if data, err := json.Marshal(bars); err == nil {
		_span.SetAttributes(attribute.String("bars", string(data)))
	} else {
		_span.SetAttributes(attribute.String("bars", fmt.Sprint(bars)))
	}
	_var0 := _d.base.G(ctx, bars)
	return _var0
}
func (_d *TracedFull) H(ctx context.Context, foos ...foo.Foo) error {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.H()")
	defer _span.End()
	if data, err := json.Marshal(foos); err == nil {
		_span.SetAttributes(attribute.String("foos", string(data)))
	} else {
		_span.SetAttributes(attribute.String("foos", fmt.Sprint(foos)))
	}
	_var0 := _d.base.H(ctx, foos...)
	if _var0 != nil {
		_span.RecordError(_var0)
		_span.SetStatus(codes.Error, _var0.Error())
	}
	return _var0
}
func (_d *TracedFull) I(ctx context.Context, foos ...[]foo.Foo) error {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.I()")
	defer _span.End()
	if data, err := json.Marshal(foos); err == nil {
		_span.SetAttributes(attribute.String("foos", string(data)))
	} else {
		_span.SetAttributes(attribute.String("foos", fmt.Sprint(foos)))
	}
	_var0 := _d.base.I(ctx, foos...)
	if _var0 != nil {
		_span.RecordError(_var0)
		_span.SetStatus(codes.Error, _var0.Error())
	}
	return _var0
}
func (_d *TracedFull) J(ctx context.Context, foos ...*[]*foo.Foo) []*[]*foo.Foo {
	var _span trace.Span
	ctx, _span = _d.tracer.Start(ctx, "Full.J()")
	defer _span.End()
	if data, err := json.Marshal(foos); err == nil {
		_span.SetAttributes(attribute.String("foos", string(data)))
	} else {
		_span.SetAttributes(attribute.String("foos", fmt.Sprint(foos)))
	}
	_var0 := _d.base.J(ctx, foos...)
	return _var0
}
